module.exports = {
  COMMUNITY_CHAT:"COMMUNITY_CHAT",
  USER_CONNECTED:"USER_CONNECTED",
  USER_DISCONNECTED:"USER_DISCONNECTED",
  MESSAGE_SENT:"MESSAGE_SENT",
  MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
  TYPING:"TYPING",
  VERIFY_USER:"VERIFY_USER",
  LOGOUT:"LOGOUT"
}
